### ISSUE TITLE
Error 500 on Badge Generation

### ISSUE THREAD

**Issue by StephenShamakian** [QualInsight/qualinsight-plugins-sonarqube-badges#76]
Hello,

Were having an issue where when we try to hit any of the badge API endpoints we get an error 500 with this text in the browser:

"{

    "errors": [
        {
            "msg": "0"
        }
    ]

}"

The log returns this:

"2017.11.13 14:19:25 ERROR web[o.s.s.w.WebServiceEngine] Fail to process request http://sonarqube/api/badges/gate?key=xxxxxxxxxxxx
java.lang.ArrayIndexOutOfBoundsException: 0
                at sun.font.CompositeFont.getSlotFont(CompositeFont.java:351) ~[na:1.8.0_144]
                at sun.font.CompositeGlyphMapper.initMapper(CompositeGlyphMapper.java:81) ~[na:1.8.0_144]
                at sun.font.CompositeGlyphMapper.<init>(CompositeGlyphMapper.java:62) ~[na:1.8.0_144]
                at sun.font.CompositeFont.getMapper(CompositeFont.java:409) ~[na:1.8.0_144]
                at sun.font.StandardGlyphVector.init(StandardGlyphVector.java:1122) ~[na:1.8.0_144]
                at sun.font.StandardGlyphVector.<init>(StandardGlyphVector.java:172) ~[na:1.8.0_144]
                at java.awt.Font.getStringBounds(Font.java:2421) ~[na:1.8.0_144]
                at java.awt.Font.getStringBounds(Font.java:2331) ~[na:1.8.0_144]
                at com.qualinsight.plugins.sonarqube.badges.font.FontProvider.computeWidth(FontProvider.java:77) ~[na:na]
                at com.qualinsight.plugins.sonarqube.badges.ws.SVGImageData$Builder.build(SVGImageData.java:233) ~[na:na]
                at com.qualinsight.plugins.sonarqube.badges.ws.gate.QualityGateBadgeGenerator.svgImageInputStreamFor(QualityGateBadgeGenerator.java:104) ~[na:na]
                at com.qualinsight.plugins.sonarqube.badges.ws.gate.QualityGateBadgeRequestHandler.handle(QualityGateBadgeRequestHandler.java:91) ~[na:na]
"

Were not sure whats wrong. Our Dev instance seems to be working fine. But we can't get it to work in Prod.

**Comment by StephenShamakian** [comment]
Any clues as to why we would be getting 500's?

**Comment by philipliberato** [comment]
I'm also seeing the same error with the following 500 response:

```javascript
{
  "errors": [
    {
      "msg": "An error has occurred. Please contact your administrator"
    }
  ]
}
```

SonarQube: `6.5.0.27846`
SVG Badges: `3.0.1`

**Comment by robertsinfosec** [comment]
Same here - any ideas on this?
