### ISSUE TITLE
Doesn't work with Sonar 7.5

### ISSUE THREAD

**Issue by dzmitry-rudnouski** [QualInsight/qualinsight-plugins-sonarqube-badges#82]
Plugin doesn't work with SonarQube 7.5

`2019.05.17 10:11:54 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.IllegalStateException: Unable to load component class com.qualinsight.plugins.sonarqube.badges.ws.BadgesWebService
        at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:65)
...
Caused by: java.lang.IllegalStateException: Unable to load component class com.qualinsight.plugins.sonarqube.badges.ws.gate.QualityGateBadgeAction
        at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:65)
...
`

**Comment by agourav1989** [comment]
Hi,
I am facing same issue in Sonarqube 7.9.1 Developer Edition. Any Solution for it?

**Comment by webben-de** [comment]
Same here

**Comment by patpatpat123** [comment]
Hello,

Same with the 8.0 as well.
This is a cool project, please keep it up!

Thank you
